config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'projects#index', as: :authenticated_root
  end

  root :to => 'home#index'

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'members/confirm/:token' => 'members#confirm', as: 'confirm_member'

  resources :comments, only: [:new, :edit, :create, :update, :destroy]
  resources :tasks, only: [:new, :edit, :create, :update, :destroy]

  resources :projects, only: [:index, :new, :edit, :create, :update, :destroy] do
    resources :members, only: [:index, :show, :new, :edit, :create, :update, :destroy]
    resources :stories, only: [:show, :new, :edit, :create, :update, :destroy] do
      get :current, :backlog, :icebox, :done, on: :collection
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :story, counter_cache: true

  validates :text, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :get_story, only: [:show, :edit, :update, :destroy]
  before_action :get_story_create, only: [:new, :create]

  def new
    @comment = @story.comments.new
  end

  def edit
  end

  def create
    @comment = @story.comments.new(comment_params)

    if @comment.save
      create_activity :new
      redirect_to edit_project_story_url(@project, @story), notice: 'Comment was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @comment.update(comment_params)
      create_activity :update
      redirect_to edit_project_story_url(@project, @story), notice: 'Comment was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    create_activity :destroy
    @comment.destroy
    redirect_to  edit_project_story_url(@project, @story)
  end

  private
  def create_activity(action)
    @comment.create_activity action, owner: current_user, recipient: @project
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def get_story
    @story = @comment.story
    @project = @story.project
  end

  def get_story_create
    @story = Story.find session[:current_story_id]
    @project = @story.project
  end

  def comment_params
    params.require(:comment).permit(:text)
  end

  def validate_resource_access
    raise('not authorized') unless @project.in? current_user.projects
  end
end

app/views/comments/_form.html.slim
= form_for @comment, html: { class: 'form-horizontal' } do |f|
  - if @comment.errors.any?
    .alert.alert-error
      button.close data-dismiss="alert" type="button"  &times;
      p #{pluralize(@story.errors.count, 'error')} prohibited this task from being saved:
      ul
        - @comment.errors.full_messages.each do |message|
          li=message

  .control-group
    = f.label :text, nil, class: 'control-label'
    .controls
      = f.text_field :text, placeholder: 'Task text'
  .control-group
    .controls
      = f.submit class: 'btn btn-primary'
  .control-group
    .controls
      = link_to 'Back', edit_project_story_path(@project, @story), class: 'btn btn-danger'

app/views/comments/_index.html.slim
table
  - @story.comments.each do |comment|
    tr
      p
        td=link_to comment.text, edit_comment_path(comment)
        td=link_to 'x', comment_path(comment), method: :delete, class: 'btn btn-danger btn-mini', data: { confirm: "Are you sure to delete this comment?" }

app/views/comments/new.html.slim
h1 New Comment
= render 'form'