config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'projects#index', as: :authenticated_root
  end

  root :to => 'home#index'

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'members/confirm/:token' => 'members#confirm', as: 'confirm_member'

  resources :comments, only: [:new, :edit, :create, :update, :destroy]
  resources :tasks, only: [:new, :edit, :create, :update, :destroy]

  resources :projects, only: [:index, :new, :edit, :create, :update, :destroy] do
    resources :members, only: [:index, :show, :new, :edit, :create, :update, :destroy]
    resources :stories, only: [:show, :new, :edit, :create, :update, :destroy] do
      get :current, :backlog, :icebox, :done, on: :collection
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  include PublicActivity::Common

  belongs_to :story, counter_cache: true

  validates :text, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :get_story, only: [:show, :edit, :update, :destroy]
  before_action :get_story_create, only: [:new, :create]

  def new
    @task = @story.tasks.new
  end

  def edit
  end

  def create
    @task = @story.tasks.new(task_params)

    if @task.save
      create_activity :new
      redirect_to edit_project_story_url(@project, @story), notice: 'Task was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @task.update(task_params)
      create_activity :update
      redirect_to edit_project_story_url(@project, @story), notice: 'Task was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    create_activity :destroy
    @task.destroy
    redirect_to  edit_project_story_url(@project, @story)
  end

  private
  def create_activity(action)
    @task.create_activity action, owner: current_user, recipient: @project
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def get_story
    @story = @task.story
    @project = @story.project
  end

  def get_story_create
    @story = Story.find session[:current_story_id]
    @project = @story.project
  end

  def task_params
    params.require(:task).permit(:text, :complete)
  end

  def validate_resource_access
    raise('not authorized') unless @project.in? current_user.projects
  end
end

app/views/tasks/_form.html.slim
= form_for @task, html: { class: 'form-horizontal' } do |f|
  - if @task.errors.any?
    .alert.alert-error
      button.close data-dismiss="alert" type="button"  &times;
      p #{pluralize(@story.errors.count, "error")} prohibited this task from being saved:
      ul
        - @task.errors.full_messages.each do |message|
          li=message

  .control-group
    = f.label :text, nil, class: 'control-label'
    .controls
      = f.text_field :text, placeholder: 'Task text'
  .control-group
    = f.label :complete, nil, class: 'control-label'
    .controls
      = f.check_box :complete
  .control-group
    .controls
      = f.submit class: 'btn btn-primary'
  .control-group
    .controls
      = link_to 'Back', edit_project_story_path(@project, @story), class: 'btn btn-danger'

app/views/tasks/_index.html.slim
table
  - @story.tasks.each do |task|
    tr
      td
        p
          - if task.complete.present?
            i.icon-ok
          - else
            i.icon-remove
          |  #{link_to task.text, edit_task_path(task)}

      td=link_to 'x', task_path(task), method: :delete, class: 'btn btn-danger btn-mini', data: { confirm: 'Are you sure to delete this task?' }

app/views/tasks/edit.html.slim
= render 'form'

app/views/tasks/new.html.slim
h1 New Task
= render 'form'