config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'projects#index', as: :authenticated_root
  end

  root :to => 'home#index'

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'members/confirm/:token' => 'members#confirm', as: 'confirm_member'

  resources :comments, only: [:new, :edit, :create, :update, :destroy]
  resources :tasks, only: [:new, :edit, :create, :update, :destroy]

  resources :projects, only: [:index, :new, :edit, :create, :update, :destroy] do
    resources :members, only: [:index, :show, :new, :edit, :create, :update, :destroy]
    resources :stories, only: [:show, :new, :edit, :create, :update, :destroy] do
      get :current, :backlog, :icebox, :done, on: :collection
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include PublicActivity::Common

  has_many :stories
  has_many :members
  has_many :users, through: :members

  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  after_action :add_me_to_project, only: :create

  def index
    @projects = current_user.projects.order(created_at: :desc).where('members.confirmed is true').page(params[:page]).per(8)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      create_activity :new
      redirect_to current_project_stories_url(@project), notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @project.update(project_params)
      create_activity :update
      redirect_to current_project_stories_url(@project), notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    create_activity :destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def create_activity(action)
    @project.create_activity action, owner: current_user
  end

  def add_me_to_project
    member = Member.new
    member.email = current_user.email
    member.name = 'Me'
    member.owner = true
    member.confirmed = true
    member.user = current_user
    member.project = @project
    member.save
  end

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def get_recent_activities(project)
    PublicActivity::Activity.order("created_at desc").where(recipient: project).limit(3)
  end
end

app/views/projects/_form.html.slim
= form_for @project, html: { class: 'form-horizontal' } do |f|
  - if @project.errors.any?
    .alert.alert-error
      button.close data-dismiss="alert" type="button"  &times;
      p #{pluralize(@project.errors.count, "error")} prohibited this project from being saved:
      ul
        - @project.errors.full_messages.each do |message|
          li=message

  .control-group
    = f.label :name, nil, class: 'control-label'
    .controls
      = f.text_field :name, placeholder: 'Project name'
  .control-group
    .controls
      = f.submit class: 'btn btn-primary'
  .control-group
    .controls
      = link_to 'Back', projects_path, class: 'btn btn-danger'

app/views/projects/edit.html.slim
.span12
  h1 Edit Project
  = render 'form'

app/views/projects/index.html.slim
.span12
  h1 Dashboard
  = link_to 'Add project', new_project_path, class: 'btn btn-primary btn-large'
  hr
- @projects.each do |project|
  .span2.well
    = link_to project.name, current_project_stories_path(project), class: 'btn btn-info'
    hr
    = render_activities get_recent_activities(project)
    hr
    = link_to 'Edit', edit_project_path(project), class: 'btn btn-primary'
    = link_to 'Delete', project_path(project), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure to delete #{project.name}?" }

.row.span12.pagination
  = paginate @projects