config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'projects#index', as: :authenticated_root
  end

  root :to => 'home#index'

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'members/confirm/:token' => 'members#confirm', as: 'confirm_member'

  resources :comments, only: [:new, :edit, :create, :update, :destroy]
  resources :tasks, only: [:new, :edit, :create, :update, :destroy]

  resources :projects, only: [:index, :new, :edit, :create, :update, :destroy] do
    resources :members, only: [:index, :show, :new, :edit, :create, :update, :destroy]
    resources :stories, only: [:show, :new, :edit, :create, :update, :destroy] do
      get :current, :backlog, :icebox, :done, on: :collection
    end
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  include PublicActivity::Common

  STATES = [ STATE_UNSTARTED = 'unstarted'.freeze,
             STATE_STARTED = 'started'.freeze,
             STATE_FINISHED = 'finished'.freeze,
             STATE_DELIVERED = 'delivered'.freeze,
             STATE_ACCEPTED = 'accepted'.freeze,
             STATE_REJECTED = 'rejected'.freeze].freeze

  STORY_TYPES = [ STORY_TYPE_FEATURE = 'feature'.freeze,
                  STORY_TYPE_BUG = 'bug'.freeze,
                  STORY_TYPE_CHORE = 'chore'.freeze,
                  STORY_TYPE_RELEASE = 'release'.freeze].freeze

  CONTAINTERS = [ CONTAINER_ICEBOX = 'icebox'.freeze,
                  CONTAINTER_BACKLOG = 'backlog'.freeze].freeze

  belongs_to :project
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_many :tasks
  has_many :comments

  validates :name, :description, presence: true
  validates :state, inclusion: { in: [STATE_UNSTARTED, STATE_STARTED, STATE_FINISHED, STATE_DELIVERED, STATE_ACCEPTED, STATE_REJECTED]}
  validates :story_type, inclusion: { in: [STORY_TYPE_FEATURE, STORY_TYPE_BUG, STORY_TYPE_CHORE, STORY_TYPE_RELEASE]}
  validates :container, inclusion: { in: [CONTAINER_ICEBOX, CONTAINTER_BACKLOG]}

  scope :current, -> {where(state: [STATE_STARTED, STATE_FINISHED, STATE_DELIVERED, STATE_REJECTED])}
  scope :icebox, -> {where(state: STATE_UNSTARTED, container: CONTAINER_ICEBOX)}
  scope :backlog, -> {where(state: STATE_UNSTARTED, container: CONTAINTER_BACKLOG)}
  scope :done, -> {where(state: STATE_ACCEPTED)}
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :get_project
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @story = @project.stories.new
  end

  def edit
    session[:current_story_id] = @story.id
  end

  def create
    @story = @project.stories.new(story_params)

    if @story.save
      create_activity :new
      redirect_to icebox_project_stories_url(@project), notice: 'Story was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @story.update(story_params)
      create_activity :update
      redirect_to current_project_stories_url(@project), notice: 'Story was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    create_activity :destroy
    @story.destroy
    redirect_to  current_project_stories_url(@project)
  end

  def current
    @stories = @project.stories.current.order('created_at desc')
  end

  def icebox
    @stories = @project.stories.icebox.order('created_at desc')
  end

  def done
    @stories = @project.stories.done.order('created_at desc')
  end

  def backlog
    @stories = @project.stories.backlog.order('created_at desc')
  end

  private
  def create_activity(action)
    @story.create_activity action, owner: current_user, recipient: @project
  end

  def get_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_story
    @story = @project.stories.find(params[:id])
  end

  def story_params
    params.require(:story).permit(:name, :state, :description, :story_type, :owner_id, :container)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_actions(story)
    links = case story.state
              when 'unstarted'
               [{ status: 'started', color: :default }]
              when 'started'
               [{ status: 'finished', color: :primary }]
              when 'finished'
               [{ status: 'delivered', color: :warning }]
              when 'delivered'
               [{ status: 'accepted', color: :success }, { status: 'rejected', color: :danger }]
              when 'rejected'
               [{ status: 'unstarted', color: :default }]
              else []
     end

    out = []

    links.each_with_object(out) do |link, obj|
      obj << link_to(link[:status], project_story_path(story.project, story, story: { state: link[:status]}), method: :put, class: "btn btn-#{link[:color]}")
    end

    out << link_to('x', project_story_path(story.project, story), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure to delete #{story.name}?" })
    out.join('').html_safe
  end

  def get_registered_members(project)
    members = []

    project.members.each do |member|
      members << member if member.user.present?
    end

    members
  end
end

app/views/stories/_form.html.slim
= form_for [@project, @story], html: { class: 'form-horizontal' } do |f|
  - if @story.errors.any?
    .alert.alert-error
      button.close data-dismiss="alert" type="button"  &times;
      p #{pluralize(@story.errors.count, "error")} prohibited this story from being saved:
      ul
        - @story.errors.full_messages.each do |message|
          li=message

  .control-group
    = f.label :name, nil, class: 'control-label'
    .controls
      = f.text_field :name, placeholder: 'Story name'
  .control-group
    = f.label :state, nil, class: 'control-label'
    .controls
      = f.select :state, [Story::STATE_UNSTARTED, Story::STATE_STARTED, Story::STATE_FINISHED, Story::STATE_DELIVERED, Story::STATE_ACCEPTED, Story::STATE_REJECTED]
  .control-group
    = f.label :description, nil, class: 'control-label'
    .controls
      = f.text_area :description
  .control-group
    = f.label :story_type, nil, class: 'control-label'
    .controls
      = f.select :story_type, [Story::STORY_TYPE_FEATURE, Story::STORY_TYPE_BUG, Story::STORY_TYPE_CHORE, Story::STORY_TYPE_RELEASE]
  .control-group
    = f.label :owner_id, nil, class: 'control-label'
    .controls
      = f.select :owner_id, get_registered_members(@project).map { |m| [m.user.email, m.user.id] }
  .control-group
    = f.label :container, nil, class: 'control-label'
    .controls
      = f.select :container, [Story::CONTAINER_ICEBOX, Story::CONTAINTER_BACKLOG]
  .control-group
    .controls
      = f.submit class: 'btn btn-primary'
  .control-group
    .controls
      = link_to 'Back', current_project_stories_path(@project), class: 'btn btn-danger'

app/views/stories/_index.html.slim
table.table.striped.table-hover
  thead
    tr
      th Name
      th State
      th Story Type
      th Owner
      th Comments
      th Tasks
      th Actions
  tbody
    - @stories.each do |story|
      tr
        td.project.name
          = link_to story.name, edit_project_story_path(story.project, story)
        td.project.state
          = story.state
        td.project.story_type
          = story.story_type
        td.project.story.owner
          = story.owner.email
        td.project.story.comments
          = story.comments_count
        td.project.story.tasks
          = story.tasks_count
        td.project.actions
          = story_actions(story)

app/views/stories/_links.html.slim
= link_to 'Current', current_project_stories_path(@project), class: 'btn btn-info'
= link_to 'Backlog', backlog_project_stories_path(@project), class: 'btn btn-info'
= link_to 'Icebox', icebox_project_stories_path(@project), class: 'btn btn-info'
= link_to 'Done', done_project_stories_path(@project), class: 'btn btn-info'
= link_to 'Add New Story', new_project_story_path(@project), class: 'btn btn-primary'
= link_to 'Members', project_members_path(@project), class: 'btn btn-primary'
= link_to 'Dashboard', projects_path, class: 'btn btn-danger'

app/views/stories/backlog.html.slim
.span12
  h1 Backlog Stories
  = render 'links'
  hr
  = render 'index'

app/views/stories/current.html.slim
.span12
  h1 Current Stories
  = render 'links'
  hr
  = render 'index'

app/views/stories/done.html.slim
.span12
  h1 Done Stories
  = render 'links'
  hr
  = render 'index'

app/views/stories/edit.html.slim
.span6
  = render 'form'
.span3
  h1 Comments
  = render 'comments/index'
  = link_to 'Add Comment', new_comment_path, class: 'btn btn-primary btn-small'
.span3
  h1 Tasks
  = render 'tasks/index'
  = link_to 'Add Task', new_task_path, class: 'btn btn-primary btn-small'

app/views/stories/icebox.html.slim
.span12
  h1 Icebox Stories
  = render 'links'
  hr
  = render 'index'

app/views/stories/new.html.slim
h1 New Story
= render 'form'